import { Container, Typography, Box } from "@mui/material";

export default function Terms() {
  return (
    <Container maxWidth="lg" sx={{ paddingTop: "20px", paddingBottom: "20px" }}>
      <Typography variant="h4" gutterBottom>
        Terms of Use
      </Typography>
      <Box sx={{ marginTop: "20px" }}>
        <Typography variant="body1" paragraph>
          Welcome to our Fantasy Sports Logo Generator. By using our service, you agree to the following terms:
        </Typography>
        <Typography variant="body1" paragraph>
          1. You are free to use the logos generated by our service for personal and commercial purposes.
        </Typography>
        <Typography variant="body1" paragraph>
          2. You may not use the logos in any way that is unlawful, harmful, or offensive.
        </Typography>
        <Typography variant="body1" paragraph>
          3. We do not guarantee the availability or functionality of the service at all times.
        </Typography>
        <Typography variant="body1" paragraph>
          4. We reserve the right to modify or discontinue the service at any time without notice.
        </Typography>
        <Typography variant="body1" paragraph>
          5. By using our service, you agree to indemnify and hold us harmless from any claims arising from your use of the logos.
        </Typography>
        <Typography variant="body1" paragraph>
          Thank you for using our service!
        </Typography>
      </Box>
    </Container>
  );
}
